// Auto-generated compilation tests for the **smartbugs-curated** dataset.
//
// Each `.sol` file gets its own `#[test]` function, generated by `build.rs`
// at compile time.  New files are picked up automatically on rebuild.

#[path = "test_utils.rs"]
mod test_utils;

include!(concat!(env!("OUT_DIR"), "/compile_smartbugs_tests.rs"));
