//! Shared test utilities for Solidity compilation tests.
//!
//! These utilities support both the **libsolidity** and **smartbugs-curated**
//! dataset tests that are auto-generated by `build.rs`.

use frontend::solidity::{
    ast::SourceUnit, ast::utils::export::export_source_unit, lowering::lower,
    parsing::parse_input_file,
};
use regex::Regex;
use std::{
    ffi::OsStr,
    fs::{self, File},
    io::{self, BufRead, Write},
    path::{Path, PathBuf},
};

// Hack to print debugging information by `info!` when running tests.
#[cfg(test)]
#[allow(unused_imports)]
use std::{println as info, println as warn};

/// Global variable to control whether to test parsing ASTs by exporting the
/// ASTs to Solidity files and invoke Solc to compile them.
pub const TEST_PARSING_AST: bool = true;

/// Global variable to control whether to test normalizing ASTs by exporting
/// the ASTs to Solidity files and invoke Solc to compile them.
pub const TEST_NORMALIZING_AST: bool = true;

/// Sanitize a source name extracted from test files so that it can be used as
/// a safe file path component. Replaces path separators and strips leading
/// slashes to prevent path traversal or root-relative paths.
fn sanitize_source_name(name: &str) -> String {
    // Strip leading path separators, then replace remaining separators
    let trimmed = name.trim_start_matches('/').trim_start_matches('\\');
    if trimmed.is_empty() {
        // Entirely composed of separators (e.g., "////") — use a safe fallback
        return "_unnamed_source_.sol".to_string();
    }
    trimmed.to_string()
}

/// Export source file.
fn export_source_file(
    source_path: &str,
    content_lines: &[String],
    output_dir: &str,
) -> Option<String> {
    let output_file_path = Path::new(output_dir).join(source_path);
    if let Some(output_dir) = output_file_path.parent() {
        std::fs::create_dir_all(output_dir).ok();
    }
    let mut output_file = match File::create(&output_file_path) {
        Ok(file) => file,
        Err(_) => panic!("Unable to create file: {}", output_file_path.display()),
    };
    output_file
        .write_all(content_lines.join("\n").as_bytes())
        .ok();

    output_file_path.to_str().map(|s| s.to_string())
}

/// Preprocess a Solidity file collected from Ethereum's Solidity test-suite.
fn preprocess_solidity_file(file_path: PathBuf) -> common::error::Result<(String, Vec<String>)> {
    info!("- Preprocess: {}", file_path.display());

    // Split content of the test file into lines to extract embedded source files
    let input_file = File::open(&file_path)?;
    let file_content_lines = io::BufReader::new(input_file).lines();
    let test_dir = file_path.parent().unwrap_or_else(|| Path::new(""));
    let output_dir = test_dir
        .join("preprocessed")
        .to_str()
        .unwrap_or("")
        .to_string();
    let mut source_name: String = file_path
        .file_name()
        .expect("Test file name should be provided")
        .to_str()
        .expect("Test file name should be provided")
        .to_string();

    let mut content: Vec<String> = vec![];
    let mut output_files: Vec<String> = vec![];

    let source_name_regex = Regex::new(r"==== Source: (.+) ====").unwrap();
    for line in file_content_lines.map_while(Result::ok) {
        // Detect a new source file
        if let Some(captures) = source_name_regex.captures(&line) {
            // Write content of the current source file first
            if !content.is_empty()
                && let Some(out_file) = export_source_file(&source_name, &content, &output_dir)
            {
                output_files.push(out_file);
            }

            // Start to record content of the new source file.
            content = vec![];
            let raw_name = captures.get(1).map_or("", |m| m.as_str()).to_string();
            source_name = sanitize_source_name(&raw_name);
        } else {
            content.push(line.clone());
        }
    }

    // Write content of the last source file
    if !content.is_empty()
        && let Some(output_file) = export_source_file(&source_name, &content, &output_dir)
    {
        output_files.push(output_file);
    }

    Ok((output_dir, output_files))
}

/// Test compiling a list of related Solidity files which can import each other.
/// The test is done by performing the following steps:
///
/// 1. Compile each file by Solc to JSON AST and parse the JSON AST to internal
///    AST.
/// 2. Export all the internal ASTs back to Solidity files.
/// 3. Compile the exported Solidity files by Solc and check if it is
///    successful.
fn test_compiling_solidity_file_inner(
    input_files: &[String],
    preprocessed_dir: &str,
    root_test_dir: &Path,
    solc_ver: &str,
) -> bool {
    let mut parsed_source_units: Vec<SourceUnit> = vec![];
    for input_file in input_files {
        match parse_input_file(input_file, Some(preprocessed_dir), &[], Some(solc_ver)) {
            Ok(source_units) => {
                // Check if source units are compiled successfully.
                assert!(
                    !source_units.is_empty(),
                    "Test export and compile source unit: no source unit is: {input_file}"
                );

                // Do not include duplicated source unit.
                for source_unit in source_units {
                    if parsed_source_units
                        .iter()
                        .all(|sunit| !&sunit.path.eq(&source_unit.path))
                    {
                        parsed_source_units.push(source_unit)
                    }
                }
            }
            Err(err) => panic!("Failed to compile: {input_file}\n\nError: {err}"),
        };
    }

    info!("- Test dir: {root_test_dir:?}");
    info!("- Preprocessed dir: {preprocessed_dir:?}");

    // Test compiling all parsed source units
    if TEST_PARSING_AST {
        info!("\n================== TEST PARSING AST ==================");
        let parsed_dir_path: PathBuf = root_test_dir.join("parsed");
        let parsed_dir = parsed_dir_path.to_str().unwrap_or("");

        let mut exported_files = vec![];
        for source_unit in parsed_source_units.iter() {
            // Prepare output file name
            info!("- Source file: {}", source_unit.path);
            let output_file = source_unit.path.replace(preprocessed_dir, parsed_dir);

            info!("- Export the parsed AST to: {output_file}");
            export_source_unit(source_unit, &output_file).ok();

            assert!(
                Path::new(&output_file).exists(),
                "Soljc failed export the original AST to: {output_file}"
            );
            exported_files.push(output_file);
        }

        // Now compile all the exported files to test if they are valid Solidity files.
        for file in exported_files.iter() {
            info!("- Test compilation: {}", file);
            if let Err(err) = parse_input_file(file, Some(parsed_dir), &[], Some(solc_ver)) {
                panic!("Failed to compile: {}\n\nError: {}", file, err);
            }
        }
    }

    // Test compiling all normalized source units
    if TEST_NORMALIZING_AST {
        info!("\n================== TEST NORMALIZING AST ==================");
        let normalized_dir_path: PathBuf = root_test_dir.join("normalized");
        let normalized_dir = normalized_dir_path.to_str().unwrap_or("");

        let normalized_source_units = lower::run_passes(&parsed_source_units);

        // Test compiling all normalized source units
        let mut exported_files = vec![];
        for source_unit in normalized_source_units.iter() {
            // Prepare output file name
            let output_file = source_unit.path.replace(preprocessed_dir, normalized_dir);

            info!("- Export normalized AST to: {output_file}");
            export_source_unit(source_unit, &output_file).ok();

            assert!(
                Path::new(&output_file).exists(),
                "Soljc failed export the normalized AST to: {output_file}"
            );

            exported_files.push(output_file);
        }

        for file in exported_files.iter() {
            // Compile the normalized Solidity file by Solc again
            info!("- Test compilation: {}", file);
            if let Err(err) = parse_input_file(file, Some(normalized_dir), &[], Some(solc_ver)) {
                panic!("Failed to compile: {}\n\nError: {}", file, err);
            }
        }
    }

    true
}

/// Standalone test for a single `.sol` file.
///
/// This is the entry point called by the auto-generated test functions.
/// It handles preprocessing (for libsolidity multi-source files) and
/// then runs the compilation test pipeline.
#[allow(dead_code)]
pub fn test_compiling_solidity_file_standalone(file_path: &str, solc_version: &str) {
    // Use `color_eyre` to print error messages in a more readable way.
    let _ = color_eyre::install();

    let test_file_path = PathBuf::from(file_path);
    assert!(test_file_path.exists(), "Test file does not exist: {file_path}");

    // Create a temporarily directory as the output test directory
    let output_path = match tempfile::tempdir() {
        Ok(temp_dir) => temp_dir.keep(),
        Err(_) => panic!("Failed to create the output test directory!"),
    };
    let root_output_dir = match output_path.as_os_str().to_str() {
        Some(dir) => dir,
        None => panic!("Failed to create the output test directory!"),
    };

    let test_file_name = test_file_path
        .file_name()
        .unwrap_or(OsStr::new("test"))
        .to_str()
        .unwrap_or("test");

    // Create a dedicated output directory for each test file.
    let root_test_dir = Path::new(root_output_dir).join(test_file_name);
    if !root_test_dir.exists() && std::fs::create_dir_all(&root_test_dir).is_err() {
        panic!("Failed to create output test directory: {}", root_test_dir.display());
    }

    // Copy file to the temporary directory
    let input_test_file = root_test_dir.join(test_file_name);
    match fs::copy(&test_file_path, &input_test_file) {
        Ok(_) => (),
        Err(err) => panic!(
            "Failed to copy test file `{:?}` to `{:?}`.\nError: {}",
            &test_file_path, &input_test_file, err
        ),
    }

    // Test files in the temporary directory
    if let Ok((preprocessed_dir, test_files)) = preprocess_solidity_file(input_test_file) {
        info!("- Start to compile: {}", test_files.join(", "));
        test_compiling_solidity_file_inner(
            &test_files,
            &preprocessed_dir,
            &root_test_dir,
            solc_version,
        );
    }
}
